### ISSUE TITLE
How to retrieve variable value

### ISSUE THREAD

**Issue by Aliefe02** [pyscada/PyScada#138]
I can see the variable value on the hmi by using variable_status page. I want to add a restframework to pyscada and I set it up. I want to retrieve the value of a variable in the code. In the database, value is not stored in variable table. I can find the value from pyscada_recordeddata but this way doesn't seem reasonable. I must order it and filter it and select the first record. That table will have maybe millions of records. How else can i access the value of a variable. In my api I want to say for example:

var = variable.objects.get(id=1) 
return var.value

this is pseudo code of course but I am not sure how to access the value.

**Comment by clavay** [comment]
if you want to get the last value only for one variable, try this code : 
```
var = variable.objects.get(id=1)
if var.query_prev_value():
        last_timestamp = var.timestamp_old
        last_value = var.prev_value
```

If you want to get values in a time range for a list of variables id, do : 
```
kwargs = {
    "variable_ids": [1,2,3,8],
    "time_min": timestamp_from,
    "time_max": timestamp_to,
}
data = Variable.objects.read_multiple(**kwargs)
```
Where `timestamp_from` and `timestamp_to` are unix timestamp in seconds
