### ISSUE TITLE
Questions for installation

### ISSUE THREAD

**Issue by Kamilcuk** [pyscada/PyScada#142]
The install_docker.sh checks for root user. Why is it needed?

Is ssl required to run pyscada? Why?

**Comment by clavay** [comment]
You may be right, try `install_docker.sh` without sudo and comment the check for root user at the begining.

Ssl is no required, you can disable it in the nginx configuration.

The `-tpl` files are used as template files to build the project configuration files as [here](https://github.com/django/django/tree/main/django/conf/project_template).
See the [docs](https://docs.djangoproject.com/en/5.0/ref/django-admin/)
