### ISSUE TITLE
This error originates from a subprocess, and is likely not a problem with pip. 

### ISSUE THREAD

**Issue by e41c9fp9duckcom** [pyscada/PyScada#156]
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [29 lines of output]
    running develop
    /home/sct/anaconda3/envs/pscada/lib/python3.11/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
    !!
    
            ********************************************************************************
            Please avoid running ``setup.py`` and ``easy_install``.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.
    
            See https://github.com/pypa/setuptools/issues/917 for details.
            ********************************************************************************
    
    !!
      easy_install.initialize_options(self)
    /home/sct/anaconda3/envs/pscada/lib/python3.11/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
    !!
    
            ********************************************************************************
            Please avoid running ``setup.py`` directly.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.
    
            See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
            ********************************************************************************
    
    !!
      self.initialize_options()
    running egg_info
    error: Cannot update time stamp of directory 'PyScada.egg-info'
    [end of output]

note: ![Screenshot from 2024-07-03 17-52-49](https://github.com/pyscada/PyScada/assets/157194887/7e285157-9f96-4647-a353-1396833b2dd7)

**Comment by e41c9fp9duckcom** [comment]
do you have any setup doct?

**Comment by clavay** [comment]
Maybe you are running the command as the pyscada user but the user don't have right to write to all files and sub-directories ?

Please provide more information about what you are doing.

**Comment by clavay** [comment]
Any news ?
If not please close the issue.

**Comment by clavay** [comment]
Please reopen if needed.
