### ISSUE TITLE
Mysql issue

### ISSUE THREAD

**Issue by michaelz152** [pyscada/PyScada#30]
Hi,

i have managed to install the softawre on a raspberry pi3 b+ by mixing the official installation document and cwraig notice. modbus tcp-ip is working fine so thanks a lot
i have a problem if i want to add mysql database i have the following message : 
 django.db.utils.ProgrammingError: (1146, "Table 'PyScada_db.pyscada_backgroundprocess' doesn't exist")
is someone have the same issue, or if someone have managed to install it ?

thanks

michael

**Comment by clavay** [comment]
Hi,

I use Mysql.
Did you do the migrations ?
What version of PyScada do you have installed ?

clavay

**Comment by michaelz152** [comment]
hi,

i use the version 0.7rc15 of piscada
i don't remember if i have made the migration because i have made a lot of thing to manage to instal piscada
and you what is your version?

thanks and good day

michael

**Comment by clavay** [comment]
Hello, 

I use the last commited version, but your version should work.
Please try to do the migrations and tell me if everything is ok :
`cd /var/www/pyscada/PyScadaServer # linux`
`sudo -u pyscada python3 manage.py migrate`

clavay

**Comment by clavay** [comment]
I think you miss this :
 sudo -u pyscada python3 manage.py pyscada_daemon init
Have you still an issue ?

**Comment by michaelz152** [comment]
hi, 

thanks for your reply 

good day 

michael 


De: "clavay" <notifications@github.com> 
À: "trombastic/PyScada" <PyScada@noreply.github.com> 
Cc: "Michaël Zerbib" <zerbib.michael@sustainair.fr>, "Author" <author@noreply.github.com> 
Envoyé: Vendredi 16 Octobre 2020 20:51:57 
Objet: Re: [trombastic/PyScada] Mysql issue (#30) 





I think you miss this : 
sudo -u pyscada python3 manage.py pyscada_daemon init 
Have you still an issue ?

**Comment by clavay** [comment]
Reopen the issue if needed.
