### ISSUE TITLE
Failed to start PyScada Daemon

### ISSUE THREAD

**Issue by apanasara** [pyscada/PyScada#36]
PySCADA Deamon is not failing to start after upgradation

![image](https://user-images.githubusercontent.com/902578/72361535-a88fe700-3717-11ea-9cdf-90d66e5225f0.png)

**Comment by clavay** [comment]
Can you put the output of journalctl -xe ?
What is your version of pyscada ?

**Comment by apanasara** [comment]
@clavay , Please refer below status

![image](https://user-images.githubusercontent.com/902578/72422248-1552c200-37a8-11ea-96ad-138f34387c4f.png)

**Comment by apanasara** [comment]
I imported _include_ by  following into urls.py but still getting error

```python
from django.conf.urls import include
```

> **Now error is**
> 1146, "Table 'PyScada_db.pyscada_backgroundprocess' doesn't exist"

![image](https://user-images.githubusercontent.com/902578/72422918-4ed7fd00-37a9-11ea-9173-e71c720570dd.png)

**Comment by clavay** [comment]
Did you successfully do this : 
`sudo -u pyscada python3 manage.py pyscada_daemon init`

**Comment by clavay** [comment]
Any news ?

**Comment by clavay** [comment]
Reopen the issue if needed.
