### ISSUE TITLE
Can't start pyscada

### ISSUE THREAD

**Issue by WorkKMc** [pyscada/PyScada#40]
I've been working on trying to set up pyscada. Every time I try the command "sudo systemctl start pyscada" it never works. I've gone through the documentation looking to find if I can figure out why the command isn't working and I just can't seem to figure out why. I'm using a raspberry pi 3 B+, the os is Raspbian jessie 8. I added a screenshot of what comes up when I run the following commands "sudo systemctl start pyscada", "sudo journalctl -xn", and "sudo systemctl status pyscada.service".
![2020-10-15-085553_1824x984_scrot](https://user-images.githubusercontent.com/72925824/96129991-5148be00-0ec5-11eb-9523-eb4104923ee1.png)

**Comment by WorkKMc** [comment]
It doesn't look like I have a pyscada_debug.log file. Should It been downloaded or did one need to be created?

**Comment by clavay** [comment]
how did you install python ?
can you show the output of : which python3

**Comment by WorkKMc** [comment]
![2020-10-16-075510_1824x984_scrot](https://user-images.githubusercontent.com/72925824/96255511-07bfa800-0f85-11eb-9909-16811861acb1.png)

**Comment by WorkKMc** [comment]
I usually use python3.6

**Comment by clavay** [comment]
and the result of :
which python3
which python3.6
?

**Comment by clavay** [comment]
try this : /usr/bin/python3 /var/www/pyscada/PyScadaServer/manage.py pyscada_daemon start

I miss the caps, the log file is there : tail -n200 /var/www/pyscada/PyScadaServer/pyscada_debug.log

**Comment by WorkKMc** [comment]
I'm sorry the try line do you mean command line or in the pyscada.service file as the ExcStart line?

**Comment by clavay** [comment]
in command line

**Comment by WorkKMc** [comment]
Ok so running that in the command line I get the first picture. I do have Dajngo installed but for python 3.6.
![2020-10-16-115821_1824x984_scrot](https://user-images.githubusercontent.com/72925824/96281208-07380900-0fa7-11eb-8dd9-dcf3fd0eed25.png)

Then I use the /home/pi/Python-3.6.5/python to run python 3.6. This is what I get running python 3.6.
![2020-10-16-115827_1824x984_scrot](https://user-images.githubusercontent.com/72925824/96281219-0acb9000-0fa7-11eb-9c74-46417f6057ff.png)

**Comment by clavay** [comment]
With your installation of python in /home/pi/Python-3.6.5 something is missing in python, but the reason doesn't seem to be pyscada nor django.
I don't know why you want to use this way of using python and how you install it.

With the normal installation of python (/usr/bin/python), you didn't follow the instructions (http://pyscada.rtfd.io) so you don't have django installed.

My suggestion is to follow the doc, and don't use another path for python, if you need a special version of python you could install it using : sudo apt-get install python3.6

Tell me if you need help for something during the installation process.

**Comment by WorkKMc** [comment]
Ok I'll let you know if it works.

**Comment by clavay** [comment]
Do you have still an issue ?

**Comment by WorkKMc** [comment]
I couldn't install python 3.6 the why you suggested. Sorry for the late respond. Other projects at work have started be higher priority.

**Comment by clavay** [comment]
Reopen the issue if needed.
