### ISSUE TITLE
I Want use it on Django>=4

### ISSUE THREAD

**Issue by EmadDeve20** [pyscada/PyScada#43]
Hello, I Want to use this on Django 4, my question is this project is dead? or it`s live?
I can contribute to this project because I need it
right now if we change the Django requirement in the setup file it is work it or we must change some code in repository?

**Comment by EmadDeve20** [comment]
Ok I do it for my self

**Comment by clavay** [comment]
Hello,
I am maintaining this repository in my fork.
I have planned to migrate to django 3 and then 4.
If you want to contribute do not hesitate to make a PR to my fork .
