### ISSUE TITLE
Table pyscada_db.pyscada_deviceprotocol doesnt exist

### ISSUE THREAD

**Issue by Karsak4747** [pyscada/PyScada#52]
When I install pycada according to the instructions or via Docker, I get the error django.db.utils.programmingerror: (1146, "table pyscada_db.pyscada_deviceprotocol doesnt exist"). How to get rid of it?
Installing on debian11

**Comment by clavay** [comment]
Hello,
I am working on the version 0.8.0 of PyScada and I will publish it soon.
It will come with a system and docker installation script.

If I have time, I will publish it today.

Your error sounds like you didn't run the migrations.
`sudo python3 /var/www/pyscada/PyScadaServer/manage.py migrate`

**Comment by Karsak4747** [comment]
Thank you very much, now the installation has worked! Please tell me how to integrate the protocols in the version with docker installation.
I'm trying to use the command: pip install pyscada-modbus
And I get the error: ERROR: Could not find a version that satisfies the requirement pyscada-modbus (from versions: none)
ERROR: No matching distribution found for pyscada-modbus

**Comment by clavay** [comment]
Try `pip3 install https://github.com/pyscada/pyscada-modbus/tarball/master` as we didn't publish it in pypi the last versions.

**Comment by Karsak4747** [comment]
Thank you very much!
